flowchart TD
    classDef stepStyle fill:#f2f0ff,line-height:1.2
    classDef externalStyle fill:#f2f0ff,line-height:1.2
    classDef defaultEventStyle fill-opacity:0
    classDef stopEventStyle fill:#bfb6fc
    classDef inputRequiredStyle fill:#f2f0ff,line-height:1.2